export const START_LOADING = 'START_LOADING';
export const FINISH_LOADING = 'FINISH_LOADING';

export const GET_ALL_ORDER_DEDAILS = 'GET_ALL_ORDER_DEDAILS';
export const SET_ORDER_DEDAILS = 'SET_ORDER_DEDAILS';